CREATE TABLE JJ_REGISTER_CLIENT_TAB(
   ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
   USERNAME VARCHAR(20) not null COMMENT '用户名',
   LOGINNAME VARCHAR(11) not null COMMENT '登录用户名--手机号',
   PASSWORD VARCHAR(20) not null COMMENT '用户密码',
   LOGOURL VARCHAR(100) COMMENT '用户图像地址',
   SUMMARY VARCHAR(200) COMMENT '用户简介',
   COMPANY VARCHAR(50) COMMENT '公司',
   POSITION VARCHAR(50) COMMENT '职位',
   CREATETIME DATE COMMENT '创建时间'
);